
FUNCTION_BLOCK addArray (*TODO: Add your comment here*) (*$GROUP=User,$CAT=User,$GROUPICON=User.png,$CATICON=User.png*)
	VAR_INPUT
		IN : ARRAY[0..1999999] OF UINT;
		PRE : ARRAY[0..1999999] OF UINT;
	END_VAR
	VAR_OUTPUT
		Q : ARRAY[0..1999999] OF UINT;
	END_VAR
	VAR
		count : UDINT;
		temp : REFERENCE TO UDINT;
	END_VAR
END_FUNCTION_BLOCK
